//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace student_learning_outcomes_management
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbStudentLearningOutcomesManagementEntities : DbContext
    {
        public dbStudentLearningOutcomesManagementEntities()
            : base("name=dbStudentLearningOutcomesManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tGiaoVien> tGiaoViens { get; set; }
        public virtual DbSet<tKetQua> tKetQuas { get; set; }
        public virtual DbSet<tKhoa> tKhoas { get; set; }
        public virtual DbSet<tKhoaHoc> tKhoaHocs { get; set; }
        public virtual DbSet<tMonHoc> tMonHocs { get; set; }
        public virtual DbSet<tSinhVien> tSinhViens { get; set; }
    }
}
