//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace student_learning_outcomes_management
{
    using System;
    using System.Collections.Generic;
    
    public partial class tKetQua
    {
        public string MaSinhVien { get; set; }
        public string MaKhoaHoc { get; set; }
        public int LanThi { get; set; }
        public Nullable<double> Diem { get; set; }
    
        public virtual tKhoaHoc tKhoaHoc { get; set; }
        public virtual tSinhVien tSinhVien { get; set; }
    }
}
