//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace student_learning_outcomes_management
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMonHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tMonHoc()
        {
            this.tKhoaHocs = new HashSet<tKhoaHoc>();
        }
    
        public string MaMonHoc { get; set; }
        public string TenMonHoc { get; set; }
        public Nullable<int> SoTietLyThuyet { get; set; }
        public Nullable<int> SoTietThucHanh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tKhoaHoc> tKhoaHocs { get; set; }
    }
}
