//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace student_learning_outcomes_management
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tSinhVien()
        {
            this.tKetQuas = new HashSet<tKetQua>();
        }
    
        public string MaSinhVien { get; set; }
        public string HoSinhVien { get; set; }
        public string TenSinhVien { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<bool> Phai { get; set; }
        public string DienThoai { get; set; }
        public string DiaChi { get; set; }
        public string MaKhoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tKetQua> tKetQuas { get; set; }
        public virtual tKhoa tKhoa { get; set; }
    }
}
